INSERT INTO "witels" ("id", "name", "abrv") VALUES (1, 'DENPASAR', 'DPS');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (2, 'JEMBER', 'JBR');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (3, 'KEDIRI', 'KDR');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (4, 'MADIUN', 'MAN');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (5, 'MADURA', 'MDR');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (6, 'MALANG', 'MLG');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (7, 'NTB', 'NTB');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (8, 'NTT', 'NTT');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (9, 'PASURUAN', 'PSN');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (10, 'SIDOARJO', 'SDA');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (11, 'SINGARAJA', 'SGR');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (12, 'SURABAYA SELATAN', 'SBS');
INSERT INTO "witels" ("id", "name", "abrv") VALUES (13, 'SURABAYA UTARA', 'SBU');
